# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9.4

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: 'cd packages/tomtom-react-searchbox && npm i'

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: test
          command: 'cd packages/tomtom-react-searchbox && npm run test'
      - run:
          name: build
          command: 'cd packages/tomtom-react-searchbox && npm run build'
      - codecov/upload:
          file: packages/tomtom-react-searchbox/coverage/lcov.info
      - store_artifacts:
          path: packages/tomtom-react-searchbox/coverage

